# Welcome to Jekyll!

# Website settings
title: "Imran Ahmed"
description: "My personal website!"
keywords: "Imran,Ahmed,CV,resume,github,linkedin,facebook, MIT, Cambridge, Computer Vision, AI"
baseurl: "/"
url: "http://www.imranahmed.io"

# author
author:
  name: 'Imran'
  first_name: 'Imran'
  last_name: 'Ahmed'
  email: '96imranahmed@gmail.com'
  facebook_username: 'ImranShahariarAhmed'
  github_username: '96imranahmed'
  linkedin_username: '96imranahmed'
  avatar: 'static/img/landing/Imran.jpg'
  desc: '
  I''m a final-year masters student currently studying <b>Information Engineering</b> at Cambridge. In terms of my experience, I have interned in a technical role at a UK-leading startup and have done research for NASA at MIT. As part of my final 
  year project, I''m developing a method of diagnosing lung diseases based on the sound coming from a stethoscope.
  <br/><br/>
  I''m actively looking for graduate roles predominantly in <b>Product Management</b> or <b>Machine Learning</b>. Please feel free to reach out (my contact details can be found below).'

# google analytics
ga:
  id: UA-89916114-1 #Personal Tracking id

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
