# Welcome to Jekyll!

# Website settings
title: "Imran Ahmed"
description: "Imran's personal website!'"
keywords: "Imran,Ahmed,CV,resume,github,linkedin,facebook"
baseurl: "/"
url: "http://www.imranahmed.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Imran'
  first_name: 'Imran'
  last_name: 'Ahmed'
  email: '96imranahmed@gmail.com'
  facebook_username: 'ImranShahariarAhmed'
  github_username: '96imranahmed'
  linkedin_username: '96imranahmed'
  avatar: 'static/img/landing/Imran.jpg'
  desc: 'I’m a third-year university student currently studying Computer Science at MIT (with an emphasis on Machine Learning). I''m part of the Cambridge-MIT Exchange Program and will return to Cambridge University to complete my masters in Information Engineering next year. <p>I''m very interested in entrepreneurship within the technology sector and I am currently looking for Product Manager Internship opportunities in these areas.</p><p>I''m a big fan of hackathons and have had the opportunity to work with some incredible people while at University on some very cool projects!</p>'
# google analytics
ga:
  id: UA-89916114-1 #Personal Tracking id

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
