# Welcome to Jekyll!

# Website settings
title: "Imran Ahmed"
description: "My personal website!"
keywords: "Imran,Ahmed,CV,resume,github,linkedin,facebook, MIT, Cambridge, Computer Vision, AI"
baseurl: "/"
url: "http://www.imranahmed.io"

# author
author:
  name: 'Imran'
  first_name: 'Imran'
  last_name: 'Ahmed'
  email: '96imranahmed@gmail.com'
  facebook_username: 'ImranShahariarAhmed'
  github_username: '96imranahmed'
  linkedin_username: '96imranahmed'
  avatar: 'static/img/landing/Imran.jpg'
  desc: '
  I''m a full-time nerd with a <b>Masters in  Information Engineering</b> at Cambridge University, currently working as a Data Scientist at <b>McKinsey QuantumBlack</b> in London. I work on developing data-driven solutions to improve the operational efficiency of systems in a range of industries. As part of my undergrad, I also studied for a year at MIT through the Cambridge-MIT Exchange.
  <br/><br/>
  In the past, I have interned in both Software Engineering and Product Managment roles at a UK-leading startup, and have researched for NASA at MIT. For my Masters thesis, I developed a method of analysing stethoscope sounds to automatically detect lung abnormalities and segment inhale/exhale cycles.
  <br/><br/>
  Please feel free to reach out (my contact details can be found below) if you are interested in getting in touch. For your interest, my resume can be found below - I am particularly interested in opportunities in either Silicon Valley or Boston. I am looking forward to hearing from you!'

# google analytics
ga:
  id: UA-89916114-1 #Personal Tracking id

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
