# Website settings
title: "Imran Ahmed"
description: "Personal website!"
keywords: "Imran,Ahmed,CV,resume,github,linkedin,MIT,Cambridge,McKinsey & Company,McKinsey,Machine Learning,Artificial Intelligence"
baseurl: "/"
url: "http://www.imranahmed.io"

# author
author:
  name: 'Imran'
  first_name: 'Imran'
  last_name: 'Ahmed'
  email: '96imranahmed@gmail.com'
  facebook_username: 'ImranShahariarAhmed'
  github_username: '96imranahmed'
  linkedin_username: '96imranahmed'
  avatar: 'static/img/landing/Imran.jpg'

# google analytics
ga:
  id: UA-89916114-1 #Personal Tracking id

# Build settings
encoding: "utf-8"