# Welcome to Jekyll!

# Website settings
title: "Imran Ahmed"
description: "My personal website!"
keywords: "Imran,Ahmed,CV,resume,github,linkedin,facebook, MIT, Cambridge, Computer Vision, AI"
baseurl: "/"
url: "http://www.imranahmed.io"

# author
author:
  name: 'Imran'
  first_name: 'Imran'
  last_name: 'Ahmed'
  email: '96imranahmed@gmail.com'
  facebook_username: 'ImranShahariarAhmed'
  github_username: '96imranahmed'
  linkedin_username: '96imranahmed'
  avatar: 'static/img/landing/Imran.jpg'
  desc: '
  I’m a third-year university student currently studying <b>Computer Science at MIT</b>. I''m part of the Cambridge-MIT Exchange Program and will return to Cambridge University to complete my masters in Information Engineering next year.
  <br/><br/>
  I''m interested in entrepreneurship within the technology sector and am currently looking for <b>Product Manager internship opportunities</b> in these areas.'

# google analytics
ga:
  id: UA-89916114-1 #Personal Tracking id

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge