# Welcome to Jekyll!

# Website settings
title: "Imran Ahmed"
description: "Imran's personal website!'"
keywords: "Imran,Ahmed,CV,resume,github,linkedin,facebook"
baseurl: "/"
url: "http://www.imranahmed.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Imran'
  first_name: 'Imran'
  last_name: 'Ahmed'
  email: '96imranahmed@gmail.com'
  facebook_username: 'ImranShahariarAhmed'
  github_username: '96imranahmed'
  avatar: 'static/img/landing/Imran.jpg'
  desc: 'I am a Full Stack engineer with website development, automation Ops and writing scripts experience. Life is a continuous learning process, so work makes me more rigorous, travel makes my life more colorful. I can make lots of friends when I coding and travel.'

# google analytics
ga:
  id: UA-89916114-1 #Personal Tracking id

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
